In order to effectively use focus information from previously imaged chips, we need to account for changes in chip location and rotation. To do this, we follow these steps:
- Find the focus and alignment at three corners. We will call these $\vec{p_{new_1}}, \vec{p_{new_2}}, \vec{p_{new_3}}$ 
- Load the corner PositionList from the previously imaged chip, $\vec{p_{prev_1}}, \vec{p_{prev_2}}, \vec{p_{prev_3}}$ 
- Find the rotation angles representing the difference in the yaw, pitch, and roll of the two lists of corners: 
$$
\cos(\alpha) = \frac{{x_{prev_2}} -{x_{prev_1}}}{XYdistance(\vec{p_{prev_2}} ,\vec{p_{prev_1}})}  - \frac{{x_{new_2}} -{x_{new_1}}}{XYdistance(\vec{p_{new_2}} ,\vec{p_{new_1}})} \\
\sin(\alpha) = \frac{{y_{prev_2}} -{y_{prev_1}}}{XYdistance(\vec{p_{prev_2}} ,\vec{p_{prev_1}})}  - \frac{{y_{new_2}} -{y_{new_1}}}{XYdistance(\vec{p_{new_2}} ,\vec{p_{new_1}})} \\
\cos(\beta) = \frac{{x_{prev_2}} -{x_{prev_1}}}{XZdistance(\vec{p_{prev_2}} ,\vec{p_{prev_1}})}  - \frac{{x_{new_2}} -{x_{new_1}}}{XZdistance(\vec{p_{new_2}} ,\vec{p_{new_1}})} \\
\sin(\beta) = \frac{{z_{prev_2}} -{z_{prev_1}}}{XZdistance(\vec{p_{prev_2}} ,\vec{p_{prev_1}})}  - \frac{{z_{new_2}} -{z_{new_1}}}{XZdistance(\vec{p_{new_2}} ,\vec{p_{new_1}})} \\
\cos(\gamma) = \frac{{y_{prev_2}} -{y_{prev_1}}}{YZdistance(\vec{p_{prev_2}} ,\vec{p_{prev_1}})}  - \frac{{y_{new_2}} -{y_{new_1}}}{YZdistance(\vec{p_{new_2}} ,\vec{p_{new_1}})} \\
\sin(\gamma) = \frac{{z_{prev_2}} -{z_{prev_1}}}{YZdistance(\vec{p_{prev_2}} ,\vec{p_{prev_1}})}  - \frac{{z_{new_2}} -{z_{new_1}}}{YZdistance(\vec{p_{new_2}} ,\vec{p_{new_1}})} \\
$$ 
- Find the translation from the origin: $$\vec{t} = \vec{p_{new_1}} - \vec{p_{prev_1}}$$
- Now, the final translation from the old focus frame to the current frame is: 
$$\vec{p_{old}} = R_{z}(\alpha)R_{y}(\beta)R_{x}(\gamma)\vec{p_{new}} + \vec{t} $$  
- Where: $$
\begin{alignat}{1}
R_x(\theta) &= \begin{bmatrix}
1 & 0 & 0 \\
0 & \cos \theta &  -\sin \theta \\[3pt]
0 & \sin \theta  &  \cos \theta \\[3pt]
\end{bmatrix} \\[6pt]
R_y(\theta) &= \begin{bmatrix}
\cos \theta & 0 & \sin \theta \\[3pt]
0 & 1 & 0 \\[3pt]
-\sin \theta & 0 & \cos \theta \\
\end{bmatrix} \\[6pt]
R_z(\theta) &= \begin{bmatrix}
\cos \theta &  -\sin \theta & 0 \\[3pt]
\sin \theta &   \cos \theta & 0\\[3pt]
0 & 0 & 1\\
\end{bmatrix}
\end{alignat}$$
- So 

In [5]:
import sys
sys.path.append('C:\\Program Files\\Micro-Manager-2.0beta')
from smartscope.source import position as pos
import numpy as np

In [171]:
def get_angle_diff(p2, p1):
    return (p2[0] - p1[0]) / np.sqrt(np.square(p2[0]-p1[0]) + np.square(p2[1]-p1[1]))

In [337]:
prev_corners = pos.load('\\00_corners', 'C:\\Users\\cell_ml\\Desktop\\20190802\\10-Control\\00\\t47')
prev_focused_pl = pos.load('\\00_focused', 'C:\\Users\\cell_ml\\Desktop\\20190802\\10-Control\\00\\t47')

new_corners = pos.load('\\00_corners', 'C:\\Users\\cell_ml\\Desktop\\20190802\\10-Control\\00\\t49')

# cos_alpha = (get_angle_diff([prev_corners[1].x, prev_corners[1].y], [prev_corners[0].x, prev_corners[0].y])
#              - get_angle_diff([new_corners[1].x, new_corners[1].y], [new_corners[0].x, new_corners[0].y]))
# sin_alpha = (get_angle_diff([prev_corners[1].y, prev_corners[1].x], [prev_corners[0].y, prev_corners[0].x])
#              - get_angle_diff([new_corners[1].y, new_corners[1].x], [new_corners[0].y, new_corners[0].x]))
    
# cos_beta = (get_angle_diff([prev_corners[1].x, prev_corners[1].z], [prev_corners[0].x, prev_corners[0].z])
#              - get_angle_diff([new_corners[1].x, new_corners[1].z], [new_corners[0].x, new_corners[0].z]))
# sin_beta = (get_angle_diff([prev_corners[1].z, prev_corners[1].x], [prev_corners[0].z, prev_corners[0].x])
#              - get_angle_diff([new_corners[1].z, new_corners[1].x], [new_corners[0].z, new_corners[0].x]))
    
# cos_gamma = (get_angle_diff([prev_corners[1].z, prev_corners[1].y], [prev_corners[2].z, prev_corners[2].y])
#              - get_angle_diff([new_corners[1].z, new_corners[1].y], [new_corners[2].z, new_corners[2].y]))
# sin_gamma = (get_angle_diff([prev_corners[1].y, prev_corners[1].z], [prev_corners[2].y, prev_corners[2].z])
#              - get_angle_diff([new_corners[1].y, new_corners[1].z], [new_corners[2].y, new_corners[2].z]))
    
# Rx = np.array([[1, 0, 0], [0, cos_gamma, -sin_gamma], [0, sin_gamma, cos_gamma]])
# Ry = np.array([[cos_beta, 0, sin_beta], [0, 1, 0], [-sin_beta, 0, cos_beta]])
# Rz = np.array([[cos_alpha, -sin_alpha, 0], [sin_alpha, cos_alpha, 0], [0, 0, 1]])
# print (Rx)
# print (Ry)
# print (Rz)


# R = np.matmul(np.matmul(Rz, Ry), Rx)
# t= np.subtract([new_corners[0].x,new_corners[0].y,new_corners[0].z], [prev_corners[0].x,prev_corners[0].y,prev_corners[0].z])
# T = np.array([[R[0][0], R[0][1],R[0][2], t[0]], 
#               [R[1][0], R[1][1],R[1][2], t[1]],
#               [R[2][0], R[2][1],R[2][2], t[2]],
#               [0, 0, 0, 1]])


# b = np.matmul(R, [new_corners[0].x, new_corners[0].y, new_corners[0].z]) + t
# print([new_corners[0].x,new_corners[0].y,new_corners[0].z])
# print (R)

In [340]:
print(prev_corners)

(-30.6,12.15,7575.8194)
(25966.025,-158.85,8435.8194)
(25908.2,-9659.3,8335.8194)



In [343]:
X = np.array([[prev_corners[0].x, prev_corners[0].y, prev_corners[0].z],
            [prev_corners[1].x, prev_corners[1].y, prev_corners[1].z],
            [prev_corners[2].x, prev_corners[2].y, prev_corners[2].z]])
Q, R = np.linalg.qr(X)
Q

array([[-8.34227269e-04, -9.46334275e-04,  9.99999204e-01],
       [ 7.07894318e-01, -7.06318362e-01, -7.78685937e-05],
       [ 7.06317874e-01,  7.07893690e-01,  1.25913469e-03]])

In [172]:
cos_alpha = get_angle_diff([new_corners[1].x, new_corners[1].y], [new_corners[0].x, new_corners[0].y])
sin_alpha = get_angle_diff([new_corners[1].y, new_corners[1].x], [new_corners[0].y, new_corners[0].x])
    
cos_beta = get_angle_diff([new_corners[1].x, new_corners[1].z], [new_corners[0].x, new_corners[0].z])
sin_beta = get_angle_diff([new_corners[1].z, new_corners[1].x], [new_corners[0].z, new_corners[0].x])
    
cos_gamma = get_angle_diff([new_corners[1].z, new_corners[1].y], [new_corners[2].z, new_corners[2].y])
sin_gamma = get_angle_diff([new_corners[1].y, new_corners[1].z], [new_corners[2].y, new_corners[2].z])

cos_alpha_prev = (get_angle_diff([prev_corners[1].x, prev_corners[1].y], [prev_corners[0].x, prev_corners[0].y]))
sin_alpha_prev = (get_angle_diff([prev_corners[1].y, prev_corners[1].x], [prev_corners[0].y, prev_corners[0].x]))
cos_beta_prev = (get_angle_diff([prev_corners[1].x, prev_corners[1].z], [prev_corners[0].x, prev_corners[0].z]))
sin_beta_prev = (get_angle_diff([prev_corners[1].z, prev_corners[1].x], [prev_corners[0].z, prev_corners[0].x]))
cos_gamma_prev = (get_angle_diff([prev_corners[1].z, prev_corners[1].y], [prev_corners[2].z, prev_corners[2].y]))
sin_gamma_prev = (get_angle_diff([prev_corners[1].y, prev_corners[1].z], [prev_corners[2].y, prev_corners[2].z]))
Rx_prev = np.array([[1, 0, 0], [0, cos_gamma_prev, -sin_gamma_prev], [0, sin_gamma_prev, cos_gamma_prev]])
Ry_prev = np.array([[cos_beta_prev, 0, sin_beta_prev], [0, 1, 0], [-sin_beta_prev, 0, cos_beta_prev]])
Rz_prev = np.array([[cos_alpha_prev, -sin_alpha_prev, 0], [sin_alpha_prev, cos_alpha_prev, 0], [0, 0, 1]])
R_prev = np.matmul(np.matmul(Rz_prev, Ry_prev), Rx_prev)

print (cos_alpha)
print (sin_alpha)
print (cos_beta)
print (sin_beta)
print (cos_gamma)
print (sin_gamma)

Rx = np.array([[1, 0, 0], [0, cos_gamma, -sin_gamma], [0, sin_gamma, cos_gamma]])
Ry = np.array([[cos_beta, 0, sin_beta], [0, 1, 0], [-sin_beta, 0, cos_beta]])
Rz = np.array([[cos_alpha, -sin_alpha, 0], [sin_alpha, cos_alpha, 0], [0, 0, 1]])
print (Rx)
print (Ry)
print (Rz)


R = np.matmul(np.matmul(Rz, Ry), Rx)
t= np.subtract([new_corners[0].x,new_corners[0].y,new_corners[0].z], [prev_corners[0].x,prev_corners[0].y,prev_corners[0].z])
T = np.array([[R[0][0], R[0][1],R[0][2], t[0]], 
              [R[1][0], R[1][1],R[1][2], t[1]],
              [R[2][0], R[2][1],R[2][2], t[2]],
              [0, 0, 0, 1]])
print (R)
print (R_prev)

0.9999392544090168
-0.011022136450777379
0.9999958411786911
-0.002884029355249555
0.0015790949983083388
0.9999987532287159
[[ 1.          0.          0.        ]
 [ 0.          0.00157909 -0.99999875]
 [ 0.          0.99999875  0.00157909]]
[[ 0.99999584  0.         -0.00288403]
 [ 0.          1.          0.        ]
 [ 0.00288403  0.          0.99999584]]
[[ 0.99993925  0.01102214  0.        ]
 [-0.01102214  0.99993925  0.        ]
 [ 0.          0.          1.        ]]
[[ 0.9999351  -0.00286645 -0.01102668]
 [-0.01102209  0.00161079 -0.99993796]
 [ 0.00288403  0.99999459  0.00157909]]
[[ 0.99943164  0.03312982 -0.00622928]
 [-0.00657404  0.01030754 -0.99992527]
 [-0.03306313  0.9993979   0.01051948]]


In [154]:
print(np.rad2deg(np.arcsin(sin_alpha_prev)))
print(np.rad2deg(np.arccos(cos_alpha_prev)))
print(sin_alpha_prev)
print(cos_alpha_prev)

0.37687342091436055
179.62312657908572
0.006577634626755585
-0.9999783671273679


In [162]:
cos = ((new_corners[1].x - new_corners[0].x)
            / (new_corners[1].dist(new_corners[0])))
sin = ((new_corners[1].y - new_corners[0].y)
            / (new_corners[1].dist(new_corners[0])))
print(sin)
print(cos)
R_test = [[cos, -sin], [sin, cos]]
for i in new_corners:
    print (np.subtract(np.matmul(np.linalg.inv(R_test),[i.x, i.y]), [new_corners[0].x, new_corners[0].y]))

-0.011022090617250282
0.999935096345549
[-0.24208699  0.2963639 ]
[2.60066209e+04 2.96363899e-01]
[26005.80263659 -9499.42922147]


In [255]:
from smartscope.source import chip
cur_chip = {'name': 'KL Chip', 'number_of_apartments': 34, 'number_of_streets': 128, 'apartment_spacing': 280.6, 'street_spacing': 194.4, 'chip_width': 26000.0, 'chip_height': 9500.0}
mchip = chip.Chip(new_corners, [-760,0], cur_chip, 5, 3)

new_focus_pl_actual = pos.load('\\00_focused', 'C:\\Users\\cell_ml\\Desktop\\20190802\\10-Control\\00\\t49')
new_focus_pl_estimated = mchip.get_focus_position_list(5,4)
print(new_focus_pl_estimated)

--------------
1197.4
-280.6
5902.59375
3074.85
(1221.22948573696,-271.9546393396566)
(7123.4401358318455,-337.01356252897176)
(13025.650785926731,-402.0724857182869)
(18927.861436021616,-467.131408907602)
(24830.072086116503,-532.1903320969172)
(24796.18081078205,-3606.8407630950283)
(18893.970160687164,-3541.7818399057132)
(12991.75951059228,-3476.7229167163982)
(7089.548860497393,-3411.6639935270828)
(1187.338210402508,-3346.6050703377678)
(1153.4469350680558,-6421.25550133588)
(7055.657585162941,-6486.314424525195)
(12957.868235257827,-6551.37334771451)
(18860.078885352712,-6616.432270903825)
(24762.2895354476,-6681.491194093141)
(24728.398260113147,-9756.14162509125)
(18826.18761001826,-9691.082701901934)
(12923.976959923375,-9626.02377871262)
(7021.766309828489,-9560.964855523305)
(1119.555659733604,-9495.90593233399)



In [177]:
for i, _ in enumerate(new_corners):
    est = np.matmul(np.linalg.inv(R), [new_corners[i].x, new_corners[i].z, new_corners[i].y])
    est1 = np.matmul(np.linalg.inv(R_prev), [prev_corners[i].x, prev_corners[i].z, prev_corners[i].y])
    print (np.subtract(est, [new_corners[0].x, new_corners[0].y, -new_corners[0].z]))
#     print (est1)
  

[-79.97701565  11.61940868   0.18727212]
[25923.5100901   -349.69226945  -212.02068111]
[25790.76158723 -9848.46260137  -210.85794062]


In [178]:
for i, _ in enumerate(new_corners):
    est = np.matmul(np.linalg.inv(R), [new_corners[i].x, new_corners[i].z, new_corners[i].y])
    est1 = np.matmul(np.linalg.inv(R_prev), [prev_corners[i].x, prev_corners[i].z, prev_corners[i].y])
#     print (np.subtract(est, [new_corners[0].x, new_corners[0].y, -new_corners[0].z]))
    print (np.subtract(est1, [prev_corners[0].x, prev_corners[0].y, -prev_corners[0].z]))

[-50.18805304  77.06698366   0.88460264]
[25931.66173647   776.29780789 -1022.79022892]
[26188.6416248  -8721.37849212 -1022.37728458]


In [182]:
yaw_cos = ((new_corners[1].x - new_corners[0].x) / dist([new_corners[0].x, new_corners[0].y], [new_corners[1].x, new_corners[1].y]))
yaw_sin = ((new_corners[1].y - new_corners[0].y) / dist([new_corners[0].x, new_corners[0].y], [new_corners[1].x, new_corners[1].y]))
roll_cos = ((new_corners[2].y - new_corners[0].y) / dist([new_corners[0].y, new_corners[0].z], [new_corners[2].y, new_corners[2].z]))
roll_sin = ((new_corners[2].z - new_corners[0].z) / dist([new_corners[0].y, new_corners[0].z], [new_corners[2].y, new_corners[2].z]))
pitch_cos = ((new_corners[1].x - new_corners[0].x) / dist([new_corners[0].x, new_corners[0].z], [new_corners[1].x, new_corners[1].z]))
pitch_sin = ((new_corners[1].z - new_corners[0].z) / dist([new_corners[0].x, new_corners[0].z], [new_corners[1].x, new_corners[1].z]))
print(sin)
print(cos)
R_test = [[roll_cos, -roll_sin], [roll_sin, roll_cos]]
for i in new_corners:
    print (np.subtract(np.matmul(np.linalg.inv(R_test),[i.y, i.z]), [new_corners[0].y, new_corners[0].z]))

-0.011022090617250282
0.999935096345549
[  -110.43168903 -14522.72738804]
[   176.89593784 -14450.36678175]
[  9675.73216933 -14522.72738804]


In [180]:
def dist (x1, x2):
    return np.sqrt(np.square(x2[0]-x1[0]) + np.square(x2[1]-x1[1]))

In [183]:
print (new_corners)

(27.0,21.825,7261.6176)
(26032.175,-264.825,7186.6176)
(25926.65,-9763.925,7171.6176)



In [284]:
def unitize (x):
    if np.sqrt(np.square(x[0]) + np.square(x[1]) + np.square(x[2])) == 0:
        return [1, 0, 0]
    return [x[0],x[1],x[2]] / np.sqrt(np.square(x[0]) + np.square(x[1]) + np.square(x[2]))

In [239]:
u =[]
new_new_corners = []
for corner in new_corners:
    new_new_corners.append([corner.x - new_corners[0].x,
                           corner.y - new_corners[0].y,
                           corner.z - new_corners[0].z])
print (new_new_corners)
n=[[],[],[]]
n[0]= unitize(new_new_corners[1])
print (new_new_corners[1])
print ((np.dot(new_new_corners[1], n[0])*n[0]))
n[1]= unitize(new_new_corners[1] - (np.dot(new_new_corners[1], n[0])*n[0]))
n[2]= np.cross(n[0], n[1])

[[0.0, 0.0, 0.0], [26005.175, -286.65, -75.0], [25899.65, -9785.75, -90.0]]
[26005.175, -286.65, -75.0]
[26005.175  -286.65    -75.   ]


In [240]:
print (n)

[array([ 0.9999351 , -0.01102209, -0.00288385]), array([-0.99987795,  0.01562309,  0.        ]), array([4.50547218e-05, 2.88350220e-03, 4.60133361e-03])]


In [204]:
R = np.transpose(n)
R

array([[ 9.99935096e-01, -9.99877952e-01,  4.50547218e-05],
       [-1.10220906e-02,  1.56230930e-02,  2.88350220e-03],
       [-2.88385416e-03,  0.00000000e+00,  4.60133361e-03]])

In [220]:
x= np.linspace(0, 26000, 20)
y= np.linspace(0, -9600, 10)
new_points = []
for i in x:
    for j in y:
        new_points.append(np.matmul(R, [i, 0, j]))

In [242]:
u =[]
new_prev_corners = []
for corner in prev_corners:
    new_prev_corners.append([corner.x - prev_corners[0].x,
                           corner.y - prev_corners[0].y,
                           corner.z - prev_corners[0].z])
print (new_prev_corners)
n=[[],[],[]]
n[0]= unitize(new_prev_corners[1])
print (new_prev_corners[1])
print((np.dot(new_prev_corners[1], n[0])*n[0]))
print(np.subtract(new_prev_corners[1], (np.dot(new_prev_corners[1], n[0])*n[0])))
n[1]= unitize(np.subtract(new_prev_corners[1], (np.dot(new_prev_corners[1], n[0])*n[0])))
n[2]= np.cross(n[0], n[1])

[[0.0, 0.0, 0.0], [25996.625, -171.0, 860.0], [25938.8, -9671.449999999999, 760.0]]
[25996.625, -171.0, 860.0]
[25996.625  -171.      860.   ]
[0. 0. 0.]


In [253]:
R2 = np.transpose(n)
x2 = np.matmul(R2, [26000,0,0])

In [269]:
print (np.matmul(R2, [prev_focused_pl[0].x, prev_focused_pl[0].y, prev_focused_pl[0].z]))
print (np.matmul(R, [0,0,0]))


[729.41927819 243.7575411   83.58690569]
[0. 0. 0.]


In [258]:
for posit in new_focus_pl_estimated:
    print (np.matmul(R, np.matmul(R2, [posit.x, posit.y, 0])))

[956.54846508 -10.46434535  -2.54978152]
[6828.77255783  -74.80849472  -18.47569177]
[12700.99665058  -139.15264408   -34.40160201]
[18573.22074334  -203.49679345   -50.32751225]
[24445.44483609  -267.84094282   -66.25342249]
[21336.90131989  -233.57827692   -57.29405301]
[15464.67722713  -169.23412756   -41.36814277]
[9592.45313438 -104.88997819  -25.44223253]
[3720.22904162  -40.54582882   -9.51632229]
[-2151.99505113    23.79832055     6.40958795]
[-5260.53856734    58.06098644    15.36895743]
[ 6.11685525e+02 -6.28316293e+00 -5.56952811e-01]
[6483.90961817  -70.62731229  -16.48286305]
[12356.13371092  -134.97146166   -32.40877329]
[18228.35780368  -199.31561103   -48.33468354]
[15119.81428747  -165.05294514   -39.37531406]
[9247.59019472 -100.70879577  -23.44940382]
[3375.36610196  -36.3646464    -7.52349357]
[-2496.85799079    27.97950297     8.40241667]
[-8369.08208355    92.32365233    24.32832691]


In [270]:
for i, posit in enumerate(new_focus_pl_estimated):
    _, _, focus_diff = (np.matmul(R, np.matmul(R2, [prev_focused_pl[i].x, prev_focused_pl[i].y, prev_focused_pl[i].z])))
    actual_focus_diff = new_focus_pl_actual[i].z 
    print (actual_focus_diff)
    print(focus_diff)

7261.6176
-1.7189275845557295
7246.6176
-18.06271614494405
7226.6176
-34.40710969222419
7206.6176
-50.75150323950433
7186.6176
-67.09589678678446
7181.6176
-58.52560517592643
7201.6176
-42.1812116286463
7221.6176
-25.83681808136616
7241.6176
-9.492424534086027
7261.6176
6.851969013194109
7256.6176
15.422260624052132
7236.6176
-0.9221329232280023
7216.6176
-17.266526470508136
7196.6176
-33.61092001778829
7176.6176
-49.95531356506841
7171.6176
-41.385324447656295
7191.6176
-25.040628406930264
7211.6176
-8.696234859650115
7231.6176
7.648158687630019
7251.6176
23.99285472835606


In [271]:
import numpy as np
import quaternion

In [321]:
def quaternion_from_two_vectors(u, v):
    norm_u_v = np.sqrt(np.square(np.linalg.norm(u))*np.square(np.linalg.norm(v))) # NOT SURE HERE 
    w = np.cross(u,v)
    q = Quaternion(norm_u_v + np.dot(u,v), w[0], w[1], w[2])
    return q.unit

In [273]:
print (new_corners)
print (prev_corners)

(27.0,21.825,7261.6176)
(26032.175,-264.825,7186.6176)
(25926.65,-9763.925,7171.6176)

(-30.6,12.15,7575.8194)
(25966.025,-158.85,8435.8194)
(25908.2,-9659.3,8335.8194)



In [274]:
u0 = np.array([prev_corners[2].x - prev_corners[0].x, prev_corners[2].y - prev_corners[0].y, prev_corners[2].z - prev_corners[0].z])
v0 = np.array([prev_corners[1].x - prev_corners[0].x, prev_corners[1].y - prev_corners[0].y, prev_corners[1].z - prev_corners[0].z])

u2 = np.array([new_corners[2].x - new_corners[0].x, new_corners[2].y - new_corners[0].y, new_corners[2].z - new_corners[0].z])
v2 = np.array([new_corners[1].x - new_corners[0].x, new_corners[1].y - new_corners[0].y, new_corners[1].z - new_corners[0].z])

# ADD CHECK FOR PARALLEL

print (u0)
print (v0)
print (u2)
print (v2)


[25938.8  -9671.45   760.  ]
[25996.625  -171.      860.   ]
[25899.65 -9785.75   -90.  ]
[26005.175  -286.65    -75.   ]


In [322]:
q2 = quaternion_from_two_vectors(u0, u2)
q2

Quaternion(0.9998798341666747, 0.005418074139239456, 0.014359908240957158, -0.0021805354288148672)

In [323]:
# v1 = q2 * v2 * np.quaternion.conjugate(q2)
# t = 2 * np.cross([q2.x, q2.y, q2.z], v2)
# v1 = v2 + q2.w * t + np.cross([q2.x, q2.y, q2.z], t)
v1 = q2.rotate(v2)
v0p = v0*unitize(u0)
v1p = v1*unitize(u0)

In [324]:
q1 = quaternion_from_two_vectors(v0p, v1p)
q= (q2*q1).unit
q

Quaternion(0.9998679776025954, 0.005439340798436528, 0.015300948188127586, -0.0005673809293511478)

In [336]:
est = []
for i, val in enumerate(prev_focused_pl):
    w0 = np.array([prev_focused_pl[i].x, prev_focused_pl[i].y,prev_focused_pl[i].z])
    w2_actual = np.array([new_focus_pl_actual[i].x, new_focus_pl_actual[i].y,new_focus_pl_actual[i].z])
    est.append(q.rotate(w0))

#     print("Origninal: ",w0)
    print ("Estimate:  ",est[-1])
    print ("Actual:    ",w2_actual)

Estimate:   [1252.69831764 -375.30739414 7537.38372025]
Actual:     [1021.8    -291.8    7261.6176]
Estimate:   [7246.0262245  -383.61154854 7583.97182808]
Actual:     [7010.9    -291.8    7246.6176]
Estimate:   [13238.74229769  -391.69781077  7610.57048412]
Actual:     [13000.      -291.8     7226.6176]
Estimate:   [19231.45837088  -399.784073    7637.16914016]
Actual:     [18989.1     -291.8     7206.6176]
Estimate:   [25224.17444407  -407.87033523  7663.76779621]
Actual:     [24978.2     -291.8     7186.6176]
Estimate:   [25219.38975137 -3379.49904711  7601.50659995]
Actual:     [24978.2        -3263.93333333  7181.6176    ]
Estimate:   [19226.67367818 -3371.41278488  7574.90794391]
Actual:     [18989.1        -3263.93333333  7201.6176    ]
Estimate:   [13233.95760499 -3363.32652265  7548.30928787]
Actual:     [13000.         -3263.93333333  7221.6176    ]
Estimate:   [ 7241.2415318  -3355.24026042  7521.71063182]
Actual:     [ 7010.9        -3263.93333333  7241.6176    ]
Estimate: 

In [334]:
import scipy
f = scipy.interpolate.interp2d(
            [p[0] for p in est], 
            [p[1] for p in est], 
            [p[2] for p in est], 
            kind='cubic')

In [335]:
print(f(1021.8, -291.8))

[7537.2377576]


In [319]:
print(prev_focused_pl)
print(new_focus_pl_actual)

(1021.8000000000002,-291.8,7575.8194)
(7010.900000000001,-291.8,7805.8194)
(13000.0,-291.8,8015.8194)
(18989.100000000002,-291.8,8225.8194)
(24978.2,-291.8,8435.8194)
(24978.2,-3263.9333333333334,8405.8194)
(18989.100000000002,-3263.9333333333334,8195.8194)
(13000.0,-3263.9333333333334,7985.8194)
(7010.900000000001,-3263.9333333333334,7775.8194)
(1021.8000000000002,-3263.9333333333334,7565.8194)
(1021.8000000000002,-6236.066666666667,7535.8194)
(7010.900000000001,-6236.066666666667,7745.8194)
(13000.0,-6236.066666666667,7955.8194)
(18989.100000000002,-6236.066666666667,8165.8194)
(24978.2,-6236.066666666667,8375.8194)
(24978.2,-9208.199999999999,8335.8194)
(18989.100000000002,-9208.199999999999,8135.8194)
(13000.0,-9208.199999999999,7925.8194)
(7010.900000000001,-9208.199999999999,7715.8194)
(1021.8000000000002,-9208.199999999999,7515.8194)

(1021.8000000000002,-291.8,7261.6176)
(7010.900000000001,-291.8,7246.6176)
(13000.0,-291.8,7226.6176)
(18989.100000000002,-291.8,7206.6176)
(24978